config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :record

      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete
    end
  end

  resources :angulars

  get 'data' => "products#data"  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    resource :configurable
  end
  

resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
 resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'
  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
      get "telephone" => "products#telephone"
      get "laptop" => "products#laptop"
      get "car" => "products#car"
    end
      resources :comments, module: :products do
    end
  end  
  
  
   
 

 

  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  
  root 'store#index'

end

app/views/shared/_down.html.haml
= stylesheet_link_tag 'application', params[:controller], media: 'all', 'data-turbolinks-track' => true 

= javascript_include_tag 'application',params[:controller], 'data-turbolinks-track' => true
= csrf_meta_tags 

app/views/shared/_navbar.html.erb
 

        <%unless user_signed_in?%>
         <div class="link_registration">
              <%= render "devise/registrations/new"%> 
              <%= render "devise/sessions/new"%>
      
          <%= render "devise/google"%>
          <%else%>
           <% if admin? %> 
            <%= link_to "admin", admin_admins_path%>
          <%end %>  
          <%= ui_button 'destroy',  t('menu.languages.sign_out'),   destroy_user_session_path, :method => :delete  %>
      </div>
    <%end%>



 <body> 
    <div class="header">

      <div class="row">


        <div class="col-md-9"> 
          <div id="site_title"><%= link_to image_tag("shop/logo.png"), root_path%></div>
            <!-- Main Menu -->
            <ol id="menu">
              <li class="active_menu_item"><%= link_to 'Category', root_path %>
                <!-- sub menu -->
                <ol>
                  <li><%= link_to 'All products', root_path %>
                  </li>
                  <li><%= link_to "Telephone", telephone_products_path %></li>
                  <li><%= link_to "Laptop", laptop_products_path %></li>
                  <li><%= link_to "Car", car_products_path %></li>
                </ol>
              </li>
              <!-- END sub menu -->
              <li><a href="#">Product</a>
                <!-- sub menu -->
                <ol>
                
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to 'Add product', new_product_path, data: { modal: true } %>
                    </li>
                  <% else %>
                    <li><%= link_to "Add product", new_user_registration_path
                      %> 
                    </li>
                  <% end %>
                </ol>

              </li>
              <!-- END sub menu -->

              <li><a href="#">Info</a>
                <ol>
                  <% if user_signed_in? %>
                    <li> <%= ui_button 'info',  t(:show_info),user_show_navbar_path(current_user.id)%></li>
                    <li><%= ui_button 'edit',  t(:edit_info), edit_info_path(current_user.id)%></li>
                    
                    <li><%= ui_button 'destroy',  t('menu.languages.sign_out'),   destroy_user_session_path, :method => :delete  %></li>
                    <%else%>
                      <%= ui_button 'info',  "show info",new_user_session_path %>
                      <%= ui_button 'edit',  "edit info", new_user_registration_path %>
                     <%end%>               
                </ol>
              </li>
              <!-- END sub menu -->
              <li><%= link_to "Contact", store_contact_path %></li> 
              <li><%= link_to "Map", store_map_path %></li> 
            </ol>
          </div>

          <div class="col-md-2">
            <%if @cart.present?%>
              <%= link_to image_tag("/assets/empty_shopping_cart.jpg", width: '72', height: '52', alt: 'Site Logo', class: "logo"), cart_path(@cart), data: { modal: true } %>
            <%end%>
          </div>  
        
          
  <%# end %>

  </div>
      </div>

 
</div>