config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :record

      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete
    end
  end

  resources :angulars

  get 'data' => "products#data"  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    resource :configurable
  end
  

resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
 resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'
  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
      get "telephone" => "products#telephone"
      get "laptop" => "products#laptop"
      get "car" => "products#car"
    end
      resources :comments, module: :products do
    end
  end  
  
  
   
 

 

  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  
  root 'store#index'

end

app/views/admin/admins/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<%= title "CMS Admin" %>

<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<style media="all" type="text/css">
@import "css/all.css";
</style>
</head>
<body>
<div id="main">
  
    <ul id="top-navigation">
      <li class="active"><span><span><%=link_to "home", root_path%></span></span></li>
       <li class="active"><span><span><%=link_to "Setting", edit_admin_configurable_path %></span></span></li>
       <li class="active"><span><span><%=link_to "Receive message", messagestoadministrators_path %></span></span></li>
       <li class="active"><span><span><%=link_to "Send message", answerfrommoderators_path %></span></span></li>  
     <!-- <li class="active"><span><span><a href="#">Users</a></span></span></li>
       <li class="active"><span><span><a href="#">Orders</a></span></span></li>
      
       <li class="active"><span><span><a href="#">Statistics</a></span></span></li>
       <li class="active"><span><span><a href="#">Design</a></span></span></li>
       <li class="active"><span><span><a href="#">Contents</a></span></span></li>-->
    </ul>

  <div id="middle">
    <div id="left-column">
      <h3>Header</h3>
      <ul class="nav">
        <li><a href="#">Lorem Ipsum dollar</a></li>
        <li><a href="#">Dollar</a></li>
        <li><a href="#">Lorem dollar</a></li>
        <li><a href="#">Ipsum dollar</a></li>
        <li><a href="#">Lorem Ipsum dollar</a></li>
        <li class="last"><a href="#">Dollar Lorem Ipsum</a></li>
      </ul>
      <a href="#" class="link">Link here</a> <a href="#" class="link">Link here</a>
    </div>
    <div id="center-column">
      <div class="top-bar"> <a href="#" class="button">ADD NEW </a>
        <h1>Contents</h1>
        <div class="breadcrumbs"> <a><%=link_to "Home", root_path%></a>
          <a><%=link_to "Setting", edit_admin_configurable_path %></a>
           <a><%=link_to "Receive message", messagestoadministrators_path %></a>
            <a><%=link_to "Send message", answerfrommoderators_path %></a>
        </div>
      </div>
   
     



      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />

        <table class="listing" cellpadding="0" cellspacing="0">
          <tr>
            <th class="first" width="177">Name</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
          <tr>
            <% @infos.each do |info| %>
              <td>
                <%= info.name %>
              </td>
              <td>
                <%= info.user.email %>
              </td>
              <td>
                <div class="btn-group closed">
                <a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="fa fa-caret-down"></span></a>
                <ul class="dropdown-menu">

                  <li> 
                    <%= link_to "Show info", info_path(info.id) %>
                  </li> 

                  <li> 
                    <%= link_to "edit",edit_info_path(info) %>
                  </li>
                  
                  <li><%= link_to "delete", delete_user_path(info.user_id),  method: :delete, data: { confirm: 'Are you sure?' }  %>
                  </li>      

                  <li> 
                    
                  </li> 
                  <% if info.ban==false %>
                    <li> <%= link_to "Ban", ban_path(info.id) %> </li> 
                  <% else %>
                    <li><%= link_to "Reban", ban_path(info.id) %> </li> 
                  <% end %>
                  </a></li>
                   
                  <li class="divider"></li>
                  <li><%= link_to "make admin", make_admin_path(info.id)%></li>
                </ul>

                </div>
              </dt>    
              <td>
                <%= info.user.role %>
              </td>
            </tr> 
          <% end %>   
        </table>

        <div class="select"> <strong>Other Pages: </strong>
          <select>
            <option>1</option>
          </select>
        </div>
      </div>




      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />
        <table class="listing form" cellpadding="0" cellspacing="0">
          <tr>
            <th class="full" colspan="2">Header Here</th>
          </tr>
          <tr>
            <td class="first" width="172"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr>
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
        </table>
        <p>&nbsp;</p>
      </div>
    </div>

  </div>
  <div id="footer"></div>
</div>
</body>
</html>












    
            <td><img src="/assets/admin/add-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/save-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/edit-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/login-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/assets/admin/add-icon.gif" width="16" height="16" alt="add" /></td>




   