config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :record

      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete
    end
  end

  resources :angulars

  get 'data' => "products#data"  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    resource :configurable
  end
  

resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
 resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'
  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
      get "telephone" => "products#telephone"
      get "laptop" => "products#laptop"
      get "car" => "products#car"
    end
      resources :comments, module: :products do
    end
  end  
  
  
   
 

 

  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  
  root 'store#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
 
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  

  def total_price
	price=product.price
    quantity*price
  end  
  


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  respond_to :html, :json, :js
  before_action :set_line_item, only: [:decrease, :increase, :show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
    respond_modal_with @product
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create

    @product=Product.find(params[:product_id])
    @line_item = @cart.add_product(product_id: @product.id)
    @line_item.price=@line_item.total_price
    if @line_item.save
      respond_to do |format|
        format.html { redirect_to store_index_path, notice: 'Line item was successfully destroyed.' }
        format.json 
        format.js 
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def increase
     @line_item.update_attribute(:quantity, @line_item.quantity+1)
     @line_item.price=@line_item.total_price
      if @line_item.save
      respond_to do |format|
        format.html { redirect_to store_index_path, notice: 'Line item was successfully destroyed.' }
        format.json 
        format.js 
      end
    end
  end
  
  def decrease
    @line_item.update_attribute(:quantity, @line_item.quantity-1)
    @line_item.price=@line_item.total_price
     if @line_item.save
      respond_to do |format|
        format.html { redirect_to store_index_path, notice: 'Line item was successfully destroyed.' }
        format.json 
        format.js 
      end
    end
  end  
  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:order_id, :price, :quantity, :product_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
  = errors_for(@line_item)

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :cart
    = f.text_field :cart
  .actions
    = f.submit 'Save'

app/views/line_items/_line_item.html.erb
<table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Quantity</th>
          <th>Price</th>
           <th>Total price</th>
           <th>Quantity</th>
            <th></th>
        </tr>
      </thead>


 <% @cart.line_items.each do |line_item| %>
      <tbody>
        <tr id="con">
      <%unless line_item.product.nil?%>
          <td><%= line_item.product.title %></td>
          <td class="count_in_<%=line_item.id%>">
            <%= render partial: "line_items/line_quantity", locals: {line_item: line_item} %>
          </td>

          <td><%= line_item.product.price %></td>
          
          <td class="count_price_<%=line_item.id%>">
            <%= number_to_currency(line_item.total_price) %>
          </td>
          
          <td><%= ui_button "add", "increase", increase_line_item_path(id: line_item.id),remote: true %>
            <%= ui_button "minus", "decrease", decrease_line_item_path(id: line_item.id), remote: true %></td>

           <td> <%#= link_to 'Delete', line_item_path(line_item), method: :delete, :data => { :confirm => 'Are you sure?' } %> <td> 

        </tr>
      </tbody>
<% end %>
<% end %>

   </table> 

app/views/line_items/_line_quantity.html.erb
<%= line_item.quantity %>

app/views/line_items/create.js.erb
$('#myModal').modal('show');
$('#modal-body').html("<%= escape_javascript(render @cart) %>");
$('.count_in_cart').html("<%= escape_javascript(render 'store/count_in_cart') %>");

app/views/line_items/decrease.js.erb
$('.count_in_<%=@line_item.id%>').html("<%= escape_javascript(render partial: 'line_items/line_quantity', locals: {line_item: @line_item}) %>");
$('.count_price_<%=@line_item.id%>').html("<%= @line_item.total_price %>");
$('.total_cell').html("<%=  all_total_price%>");

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item

= link_to 'Back', line_items_path

app/views/line_items/increase.js.erb
$('.count_in_<%=@line_item.id%>').html("<%= escape_javascript(render partial: 'line_items/line_quantity', locals: {line_item: @line_item}) %>");
$('.count_price_<%=@line_item.id%>').html("<%= @line_item.total_price %>");
$('.total_cell').html("<%=  all_total_price%>");

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %thead
    %tr
      %th Product
      %th Cart
      %th
      %th
      %th

  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item
zz
= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product
%p
  %b Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)

= link_to 'Back', line_items_path