config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :record

      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete
    end
  end

  resources :angulars

  get 'data' => "products#data"  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins, only: [:index] 
    resource :configurable
  end
  

resources :infos, :messagestoadministrators, :answerfrommoderators, :orders, :line_items, :carts
  
 resources :searches do 
    collection do
      post "product" => "searches#search_product"
    end
  end

  
  get 'home/index'
  get 'store/map'
  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
      get "telephone" => "products#telephone"
      get "laptop" => "products#laptop"
      get "car" => "products#car"
    end
      resources :comments, module: :products do
    end
  end  
  
  
   
 

 

  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get '/ban_the_user/:id' => 'admin/admins#ban_the_user', :as => 'ban'
  get '/make_admin/:id' => 'admin/admins#make_admin', :as => 'make_admin'
  delete 'user_delete/:id' => 'admin/admins#delete_user', as: "delete_user"

  
  root 'store#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
 belongs_to :user
 
 belongs_to :comment

 @model_of_attachment='photo'.parameterize.underscore.to_sym
 @validation=false
  include ValidationsForPicture
 
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_info, only: [:show,:edit, :update, :destroy]
  before_action :define_eccept, only: [:edit, :update, :destroy]
   before_action :only_admin_or_moderator, only: [:index]
  # GET /infos
  # GET /infos.json
  def index
   redirect_to "/admin/admins"
  end

  def show_from_navbar
    @info =Info.find_by(user_id: params[:user_id])
    @user=User.find(params[:user_id])
    render "infos/show"
  end

  #def show_from_email
    # @info =Info.find_by(32)
    # render "show"
  #end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @user=@info.user
  end

  # GET /infos/new
  def new
    @info = Info.new
  end
 
  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)
    @info.user_id=current_user.id
    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
       # format.js 
      
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
       # format.js 
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.  
  def define_eccept
    if current_user.info.id==@info.id || can_manage_has_one(current_user.info, @info, Info)
      return true
    else
      redirect_to root_path 
    end
  end

  def set_info
    begin
      @info=Info.find(params[:id])
    rescue
      raise Cinema::NotFound 
    end
  end 
    # Never trust parameters from the scary internet, only allow the white list through.
  def info_params
    params.require(:info).permit(:send_new_film, :send_comments_to_film, :ban, :data, :name, :city, :user_id, :bio, :telephone, :photo)
  end

end

app/helpers/infos_helper.rb
module InfosHelper
  
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
 
  <%= errors_for(@info) %>


<div class="col-md-6">
    <div class="bs-example" data-example-id="striped-table">
    <table class="table table-striped">

        <tbody>
          <td> <%= f.label :Add_photo %> </td>
          <td> <%= f.file_field :photo %> </td>
        </tbody>

       <tbody>
          <td> <%= f.label :name %> </td>
          <td> <%= f.text_field :name, size: 40 %> </td>
        </tbody>




       <tbody>
          <td> <%= f.label :website %> </td>
       <td><%= f.text_field :data, size: 40 %> </td>
        </tbody>

       <tbody>
          <td> <%= f.label :telephone %> </td>
           <td><%= f.text_field :telephone, size: 40 %> </td>
       </tbody>
       
        <tbody>
          <td> <%= f.label :bio %> </td>
         <td>  <%= f.text_area :bio, rows: 3, cols: 40 %> </td>
        </tbody>

 

       <tbody>
          <td> <%= f.label :send_new_product %> </td>
           <td><%= f.check_box :send_new_film %> </td>
       </tbody>

        <tbody>
        <td>   <%= f.label :send_comments_to_product %></td>
          <td> <%= f.check_box:send_comments_to_film %> </td>
       </tbody>


        <tbody>
         <td> <%= f.submit %></td>
          </table>
 </table> 
  </div>
  </div>

<% end %>

app/views/infos/_form.html.haml
= form_for @info do |f|
  - if @info.errors.any?
    #error_explanation
      %h2= "#{pluralize(@info.errors.count, "error")} prohibited this info from being saved:"
      %ul
        - @info.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/infos/_index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>CMS Admin</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<style media="all" type="text/css">
@import "css/all.css";
</style>
</head>
<body>
<div id="main">
  <div id="header"> <a href="#" class="logo"><img src="/assets/logo.gif" width="101" height="29" alt="" /></a>
    <ul id="top-navigation">
      <li class="active"><span><span>Homepage</span></span></li>
       <li class="active"><span><span><a href="#">Users</a></span></span></li>
       <li class="active"><span><span><a href="#">Orders</a></span></span></li>
       <li class="active"><span><span><a href="#">Settings</a></span></span></li>
       <li class="active"><span><span><a href="#">Statistics</a></span></span></li>
       <li class="active"><span><span><a href="#">Design</a></span></span></li>
       <li class="active"><span><span><a href="#">Contents</a></span></span></li>
    </ul>
  </div>
  <div id="middle">
    <div id="left-column">
      <h3>Header</h3>
      <ul class="nav">
        <li><a href="#">Lorem Ipsum dollar</a></li>
        <li><a href="#">Dollar</a></li>
        <li><a href="#">Lorem dollar</a></li>
        <li><a href="#">Ipsum dollar</a></li>
        <li><a href="#">Lorem Ipsum dollar</a></li>
        <li class="last"><a href="#">Dollar Lorem Ipsum</a></li>
      </ul>
      <a href="#" class="link">Link here</a> <a href="#" class="link">Link here</a>
    </div>
    <div id="center-column">
      <div class="top-bar"> <a href="#" class="button">ADD NEW </a>
        <h1>Contents</h1>
        <div class="breadcrumbs"><a href="#">Homepage</a> / <a href="#">Contents</a>
        </div>
      </div>
   
     



      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />

        <table class="listing" cellpadding="0" cellspacing="0">
          <tr>
            <th class="first" width="177">Name</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
          <tr>
            <% @infos.each do |info| %>
              <td>
                <%= info.name %>
              </td>
              <td>
                <%= info.user.email %>
              </td>
              <td>
                <div class="btn-group closed">
                <a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="fa fa-caret-down"></span></a>
                <ul class="dropdown-menu">

                  <li> 
                    <%= link_to "Show info", info_path(info.id) %>
                  </li> 

                  <li> 
                    <%= link_to "edit",edit_info_path(info) %>
                  </li>
                  
                  <li><%= link_to "delete", delete_user_path(info.user_id),  method: :delete, data: { confirm: 'Are you sure?' }  %>
                  </li>      

                  <li> 
                    <%= link_to "ban",ban_path(info) %>
                  </li> 
                  <% if info.ban==false %>
                      Ban
                      <% else %>
                          Reban
                      <% end %>
                  </a></li>
                   
                  <li class="divider"></li>
                  <li><%= link_to "make admin", root_path%></li>
                </ul>

                </div>
              </dt>    
              <td>
                <%= info.user.role %>
              </td>
            </tr> 
          <% end %>   
        </table>

        <div class="select"> <strong>Other Pages: </strong>
          <select>
            <option>1</option>
          </select>
        </div>
      </div>




      <div class="table"> <img src="/assets/admin/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/assets/admin/bg-th-right.gif" width="7" height="7" alt="" class="right" />
        <table class="listing form" cellpadding="0" cellspacing="0">
          <tr>
            <th class="full" colspan="2">Header Here</th>
          </tr>
          <tr>
            <td class="first" width="172"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr>
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
        </table>
        <p>&nbsp;</p>
      </div>
    </div>

  </div>
  <div id="footer"></div>
</div>
</body>
</html>












    
            <td><img src="/assets/admin/add-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/save-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/edit-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/login-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/assets/admin/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/assets/admin/add-icon.gif" width="16" height="16" alt="add" /></td>




   

app/views/infos/_show.html.erb
<div class="col-md-2">

</div>

<div class="col-md-8">
    <div class="bs-example" data-example-id="striped-table">

    <table class="table table-striped">
    <% present(@info) do |info_presenter| %>
    <tbody>
      <td><%= info_presenter.avatar %></td>
      <td><%= info_presenter.name %></td>
    </tbody>
   <tbody>
 <% if send_message(@info)%>
   <td><%#= link_to 'Send message', new_message_path(user_to: @info) %> 
   <% end %> 
<% if user_signed_in? %>
<% if can_manage_has_one(current_user.info, @info, Info)%>
 <%= link_to 'Edit', edit_info_path(@info) %> 
   <%= link_to 'Back', infos_path %> 
 </td>
<% end %>
<% end %>
 </tbody>


    <tbody>
      
      <td>Username:</td>
      <td><%= info_presenter.username %>
    </tbody>
    <tbody>
    <td>Member Since: </td>
      <td><%= @info.created_at.strftime("%B %e %Y") %>
    </td>
     </tbody> 



      <tbody> <td>Website:  </td>
      <td><%= markdown(info_presenter.website) %>
    </tbody>


      <tbody>
      <td>User: </td>
      <td> <%= @info.user.email %> </td>
    </tbody>


     <tbody> 
      <td>Telephone: 
      </td>
      <td><%= info_presenter.telephone %>
    </tbody>



    <tbody> <td>Bio:  </td>
            <td><%= markdown(info_presenter.bio) %>
    </tbody>
    <tbody> 
      <td>Film created: 
      </td>
      <td><%= render partial: "infos/user_created", locals:{user: @user} %>
    </tbody>

    <tbody>
      <td> send_new_film: </td>
      <td> <% if @info.send_new_film %>

 <%= image_tag("stock_check-filled.png", alt: 'True', class: "true_or_false") %>
     <% else %>
     <%= image_tag("x_mark_pc.png", alt: 'True', class: "true_or_false") %>
     <% end %>
      </dt>
            </tbody>
                  

                  <tbody>
     <td>send_comments_to_film:  </td>
    
     <td>  <% if @info.send_comments_to_film %>
     <%= image_tag("stock_check-filled.png", alt: 'True', class: "true_or_false") %>
     <% else %>
     <%= image_tag("x_mark_pc.png", alt: 'True', class: "true_or_false") %>
     <% end %>
   </td>
    </tbody>

    <tbody>
   
    </tbody>
    <% end %>

    </table>
    </div>
</div>





<div class="col-md-2">


</div>

app/views/infos/_user_created.html.erb
<%if @user.products.present?%>
  <% @user.products.each do |product|%>
	<%=link_to "#{product.title.capitalize}", product_path(product.id)%>
  <%end%>
<%else%>
  "User doesn't add any product"
<%end%> 

app/views/infos/create.js.erb
alert("Infos created!")

app/views/infos/edit.html.erb
<% provide(:title, 'Edit info') %>


<div class="col-md-2">
  <%=ui_button 'back',  t(:back), @info%>
  <%=ui_button 'show',  t(:show), infos_path%>
</div>

<div class="col-md-8">
  <div class="bs-example" data-example-id="striped-table">
    <table class="table table-striped">
	  <tbody>
	    <td> <%= render 'form' %> 
	    </td>
	  </tbody>
   <tbody>
  </div>
</div>

<div class="col-md-2">


</div>

app/views/infos/index.html.haml
%h1 Listing infos

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @infos.each do |info|
      %tr
        %td= link_to 'Show', info
        %td= link_to 'Edit', edit_info_path(info)
        %td= link_to 'Destroy', info, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Info', new_info_path

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/new.html.haml
%h1 New info

= render 'form'

= link_to 'Back', infos_path

app/views/infos/show.html.erb
<%=render "show"%>

app/views/infos/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_info_path(@info)
\|
= link_to 'Back', infos_path

app/views/infos/show_from_navbar.html.erb
<% provide(:title, 'infos of user') %>

<%= render partial: "show" %>

app/views/infos/update.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_task').append('<%= j render(@info) %>');